name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        configuration: [RiotGamesServers]
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64

      - name: 切换依赖库
        shell: bash
        run: |
          git clone --depth=1 https://github.com/ocornut/imgui -b v1.88
          mv -f imgui/backends/* imgui/
          mv -f imgui/* R3nzSkin/imgui/
          sed -i '2i #define IMGUI_DEFINE_MATH_OPERATORS' R3nzSkin/imgui/imgui.h
          git status

      - name: Build
        shell: cmd
        run: msbuild R3nzSkin/R3nzSkin.vcxproj -p:Instruction_Set=AdvancedVectorExtensions2 /p:Platform=x64 /p:Configuration=${{ matrix.configuration }}

      - name: Upload To Artifact_Global
        uses: actions/upload-artifact@main
        with:
          name: ${{ github.job }}-${{ matrix.os }}-${{ matrix.configuration }}
          path: R3nzSkin/Release/RiotGamesServers
